### ISSUE TITLE
Not working on Win10 Pro x64

### ISSUE THREAD

**Issue by msauza** [aloneguid/docker-explorer-windows#1]
I installed and started the application but it crashed and closed automatically. That happened in both sections containers and images.

Client: Docker Engine - Community
Version: 18.09.2
API version: 1.39
Go version: go1.10.8
Git commit: 6247962
Built: Sun Feb 10 04:12:31 2019
OS/Arch: windows/amd64
Experimental: false

Server: Docker Engine - Community
Engine:
Version: 18.09.2
API version: 1.39 (minimum version 1.12)
Go version: go1.10.6
Git commit: 6247962
Built: Sun Feb 10 04:13:06 2019
OS/Arch: linux/amd64
Experimental: true

I will glad to provide more info if it is needed.

**Comment by idealist1508** [comment]
Can you check EventLog for .NET Runtime errors?

**Comment by idealist1508** [comment]
I think, i have same issue.
There is an following error in eventlog:
```
Anwendung: DockerExplorer.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.Threading.AbandonedMutexException
   bei Squirrel.SingleGlobalInstance.Finalize()

```
To fix this you need to change 
https://github.com/aloneguid/docker-explorer-windows/blob/1d80aa9ef828a2fca1c4f75a2440ca375f83bbd2/DockerExplorer/Program.cs#L37
in 
```
            await mgr.UpdateApp();
```

**Comment by aloneguid** [comment]
@idealist1508 just pushed an update v1.5 with this fix, let me know if you have any issues now?

**Comment by idealist1508** [comment]
Thanks! It works well.
