### ISSUE TITLE
Malwarebytes does not approve

### ISSUE THREAD

**Issue by Vaelek** [aloneguid/docker-explorer-windows#2]
![image](https://user-images.githubusercontent.com/293765/56434593-d3d5ca80-629a-11e9-9489-666dac106a04.png)

https://blog.malwarebytes.com/detections/machinelearning-anomalous-100/

**Comment by aloneguid** [comment]
Thanks but I doubt I'll ever look at this. If you are concerned about security of this software, the source code is open and you can see it's not a malware ;)
